/*
 * Created on 20 févr. 2017 ( Time 04:19:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.eugena.webservice.rest.bean;

import java.io.Serializable;


/**
 * Java bean for 'TypeConge' entity
 * 
 * @author Telosys Tools
 *
 */
public class TypeConge implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_type_conge INT 
    private Integer idTypeConge;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : code VARCHAR 
    private String code;

    // DB : label VARCHAR 
    private String label;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTypeConge( Integer idTypeConge ) {
        this.idTypeConge = idTypeConge ;
    }

    public Integer getIdTypeConge() {
        return this.idTypeConge;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    public void setLabel( String label ) {
        this.label = label;
    }
    public String getLabel() {
        return this.label;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTypeConge);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(label);
        return sb.toString(); 
    } 


}
