/*
 * Created on 20 févr. 2017 ( Time 04:16:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.eugena.webservice.rest.dao;

import fr.eugena.webservice.rest.bean.Collaborateur;


/**
 * Collaborateur DAO interface
 * 
 * @author Telosys Tools
 */
public interface CollaborateurDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idCollaborateur
	 * @return the bean found or null if not found 
	 */
	public Collaborateur find( Integer idCollaborateur ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param collaborateur
	 * @return true if found, false if not found
	 */
	public boolean load( Collaborateur collaborateur ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param collaborateur
	 */
	public void insert(Collaborateur collaborateur) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param collaborateur
	 * @return
	 */
	public int update(Collaborateur collaborateur) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idCollaborateur
	 * @return
	 */
	public int delete( Integer idCollaborateur ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param collaborateur
	 * @return
	 */
	public int delete( Collaborateur collaborateur ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idCollaborateur
	 * @return
	 */
	public boolean exists( Integer idCollaborateur ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param collaborateur
	 * @return
	 */
	public boolean exists( Collaborateur collaborateur ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	/**
	 * Récupère un collaborateur en fonction de son login et password
	 * @param login
	 * @param password
	 * @return
	 */
	public Collaborateur findByLoginAndPassword(String login, String password);

}
