/*
 * Created on 20 févr. 2017 ( Time 04:16:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.eugena.webservice.rest.dao;

import java.util.List;

import fr.eugena.webservice.rest.bean.Collaborateur;
import fr.eugena.webservice.rest.bean.Cra;


/**
 * Cra DAO interface
 * 
 * @author Telosys Tools
 */
public interface CraDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idCra
	 * @return the bean found or null if not found 
	 */
	public Cra find( Integer idCra ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param cra
	 * @return true if found, false if not found
	 */
	public boolean load( Cra cra ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param cra
	 */
	public void insert(Cra cra) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param cra
	 * @return
	 */
	public int update(Cra cra) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idCra
	 * @return
	 */
	public int delete( Integer idCra ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param cra
	 * @return
	 */
	public int delete( Cra cra ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idCra
	 * @return
	 */
	public boolean exists( Integer idCra ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param cra
	 * @return
	 */
	public boolean exists( Cra cra ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;
	
	/**
	 * Récupère une liste de CRA associés à un collaborateur
	 * @param login
	 * @param password
	 * @return
	 */
	public List<Cra> findByCollaborateur(Collaborateur collaborateur);

}
