/*
 * Created on 20 févr. 2017 ( Time 04:16:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package fr.eugena.webservice.rest.dao;

import fr.eugena.webservice.rest.bean.TypeConge;


/**
 * TypeConge DAO interface
 * 
 * @author Telosys Tools
 */
public interface TypeCongeDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idTypeConge
	 * @return the bean found or null if not found 
	 */
	public TypeConge find( Integer idTypeConge ) ;

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param typeConge
	 * @return true if found, false if not found
	 */
	public boolean load( TypeConge typeConge ) ;
	
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param typeConge
	 */
	public void insert(TypeConge typeConge) ;

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param typeConge
	 * @return
	 */
	public int update(TypeConge typeConge) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param idTypeConge
	 * @return
	 */
	public int delete( Integer idTypeConge ) ;

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param typeConge
	 * @return
	 */
	public int delete( TypeConge typeConge ) ;

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idTypeConge
	 * @return
	 */
	public boolean exists( Integer idTypeConge ) ;

	//----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param typeConge
	 * @return
	 */
	public boolean exists( TypeConge typeConge ) ;

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;

}
